version: '3.3'

services:
  mysql-server:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/db
    restart: always
    env_file: .env

  assessmentsvc:
    image: assessmentsvc:debug
    build: 
      context: ../Assessmentsvc
      dockerfile: Dockerfile
    depends_on:
      - mysql-server
    restart: always
    ports:
      - 8080:80
    env_file: .env

  assessmetl:
    image: assessmetl:debug
    build: 
      context: ../AssessMETL
      dockerfile: Dockerfile
    depends_on:
      - assessmentsvc
    ports:
      - 5000:80
      
    env_file: .env

volumes:
  dbdata: