version: '3.3'

services:
  mysql-server:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/db
    restart: always
    env_file: .env

  assessmentsvc:
    image: sonofsisyphus/assessmentsvc:latest
    depends_on:
      - mysql-server
    restart: always
    env_file: .env

  assessmetl:
    image: sonofsisyphus/assessmetl:latest
    depends_on:
      - assessmentsvc
    ports:
      - 5000:80
      
    env_file: .env

volumes:
  dbdata: