version: '3.3'

services:

  assessmentsvc:
    image: sonofsisyphus/assessmentsvc:latest
    ports:
      - 8080:80
    env_file: .env

  assessmetl:
    image: sonofsisyphus/assessmetl:latest
    depends_on:
      - assessmentsvc
    ports:
      - 5000:80
      
    env_file: .env

